#in0dex:
#    path: /
#    controller: App\Controller\DefaultController::index

lemonway_moneyinwebinit:
    path: /api/v1/lemonway/MoneyInWebInit
    controller: App\Controller\Lemonway\MoneyInWebInitController